### ISSUE TITLE
Wow!

### ISSUE THREAD

**Issue by egarreau** [nikpowpie/nikpowpie.github.io#1]
Nikki, your website is beautiful! I was just scrolling through the #DBCmysite tag on twitter and I happened across yours -- I am so impressed! I really like the fixed social media sidebar and the boxed blog posts with drop shadow. I think I might steal some of your design elements for my site once I refactor it. Now that I know what a great designer you are I feel even luckier to have paired with you :smile:

**Comment by nikpowpie** [comment]
Evangeline! Thanks so much! This web dev stuff is hard work! YOUR SITE IS
BEAUTIFUL TOO! Please, feel free to steal whatever you want, I'm happy to
share! I hope we can pair again soon!
